os: linux
language: generic
dist: trusty
sudo: required
services: docker

git:
  submodules: false
before_install:
- echo -e "machine github.com\n  login $CI_TOKEN" > ~/.netrc
- git submodule update --init --recursive

jobs:
  include:
    - stage: test_and_build
      before_script:
        - docker build -t swerver:latest .
        - docker run --detach -p 5000:5000 swerver:latest
      script:
        - ./Scripts/acceptance_tests.sh
        - docker stop $(docker ps -aq)

    - stage: deploy
      script:
        ./Scripts/deploy.sh

stages:
  - name: test_and_build
  - name: deploy
    if: branch == master