env:
  global:
  - SWIFT_BRANCH=swift-4.1.3-release
  - SWIFT_VERSION=swift-4.1.3-RELEASE

os: linux
language: generic
dist: trusty
sudo: required
services: docker

install:
- sudo apt-get update
- sudo apt-get install clang libicu-dev
- mkdir swift
- curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
- export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"

jobs:
  include:
    - stage: test
      script:
        - swift package clean
        - swift build -Xswiftc -suppress-warnings
        - swift test -Xswiftc -suppress-warnings

    - stage: deploy
      script:
      - docker --version
      - pip install --upgrade pip
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker build -t $APP_NAME .
      - docker tag $APP_NAME:latest $AWS_ECR_ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/$APP_NAME:latest
      - docker push $AWS_ECR_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest
      - aws ecs update-service --cluster $AWS_ECS_CLUSTER --service $AWS_ECS_SERVICE --force-new-deployment

stages:
  - name: test
  - name: deploy
    if: branch == master

