language: objective-c
osx_image: xcode9.4
xcode_project: Swerver.xcodeproj
xcode_scheme: Swerver-Package
xcode_sdk: macosx10.13
before_script:
- gem install xcpretty
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme Swerver-Package clean build test | xcpretty


# install: swift package update
# script:
#     - swift build
#     - swift test
