language: swift
os: osx
osx_image: xcode9.4
before_script:
- gem install xcpretty
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme Swerver-Package clean build test | xcpretty
