language: objective-c
osx_image: xcode9.4
xcode_project: Swerver.xcodeproj
xcode_scheme: Swerver-Package
xcode_sdk: macosx10.13
script:
    - xcodebuild clean
before_install:
  git clone https://github.com/IBM-Swift/BlueSocket.git
